### ISSUE TITLE
这是怎么回事？

### ISSUE THREAD

**Issue by 1627461649** [sixone-Jiang/LHCXAutoFishingPro#1]
(lhcx) D:\LHCX>python main.py
ADB PATH >>>> D:/LHCX/adb/adb.exe
检测设备连接状态 >>> 127.0.0.1:7555 ...

设备列表：
127.0.0.1:7555  device

设备已连接

屏幕分辨率: Physical size: 1280x720
像素密度: Physical density: 240
系统类型: x86_64
系统版本: 6.0.1

第{0}轮钓鱼开始
WARNING:root:[Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x0000012D7D893CE0>, retrying in 0.5 seconds...
WARNING:root:[Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x0000012D7D893CE0>, retrying in 0.6 seconds...
WARNING:root:[Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x0000012D0F2C5DF0>, retrying in 0.7 seconds...
WARNING:root:[Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x0000012D0F2C5DF0>, retrying in 0.7999999999999999 seconds...
Traceback (most recent call last):
  File "D:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\uiautomator2\__init__.py", line 946, in screenshot
    return Image.open(buff).convert("RGB")
  File "D:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000012D0F2C5DF0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\LHCX\main.py", line 20, in <module>
    RunApi.run_fish(adb, d, baits_list)
  File "D:\LHCX\bin\RunApi.py", line 33, in run_fish
    StartFish.window_capture(d=d,filename=work_dir+'/temp_images/screen_fish.jpg',mumu_left=mumu_left,mumu_top=mumu_top)  File "D:\LHCX\bin\StartFish.py", line 55, in window_capture
    img = d.screenshot() # x,y,w,h
  File "D:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "D:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "D:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\uiautomator2\__init__.py", line 952, in screenshot
    raise IOError("PIL.Image.open IOError", ex)
OSError: [Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x0000012D0F2C5DF0>

**Comment by 1627461649** [comment]
解决了
