### ISSUE TITLE
大佬这该怎么解决？

### ISSUE THREAD

**Issue by 1627461649** [sixone-Jiang/LHCXAutoFishingPro#3]
(lhcx) D:\LHCX\adb>python -m uiautomator2 init
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\__init__.py", line 27, in <module>
    from . import urllib3
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 29, in <module>
    from .connection import (
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\urllib3\connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\urllib3\util\__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\urllib3\util\connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\urllib3\util\wait.py", line 1, in <module>
    from .selectors import (
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\urllib3\util\selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\dell\miniconda3\envs\lhcx\lib\collections\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\uiautomator2\__init__.py", line 40, in <module>
    import adbutils
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\adbutils\__init__.py", line 14, in <module>
    from ._device import AdbDevice, Sync
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\adbutils\_device.py", line 31, in <module>
    import requests
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\__init__.py", line 60, in <module>
    from . import utils
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\compat.py", line 11, in <module>
    from .packages import chardet
  File "C:\Users\dell\miniconda3\envs\lhcx\lib\site-packages\requests\packages\__init__.py", line 29, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

**Comment by 1627461649** [comment]
解决了
